/*
 * MIT License
 *
 * Copyright (c) 2025 <#author_name#>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#pragma once

#include "movement.h"

/*
 * A DESCRIPTION OF YOUR WATCH FACE
 *
 * and a description of how use it
 *
 */

typedef struct {
    // Anything you need to keep track of, put it here!
    uint8_t unused;
    unsigned int counter;
} wordoftheday_state_t;

void wordoftheday_face_setup(uint8_t watch_face_index, void ** context_ptr);
void wordoftheday_face_activate(void *context);
bool wordoftheday_face_loop(movement_event_t event, void *context);
void wordoftheday_face_resign(void *context);

#define wordoftheday_face ((const watch_face_t){ \
    wordoftheday_face_setup, \
    wordoftheday_face_activate, \
    wordoftheday_face_loop, \
    wordoftheday_face_resign, \
    NULL, \
})

static const char words[][6][7] = {
  { "SEi  ", "AbSEnT"},
  { "CRY  ", "WOLF  "},
  { "REAd ", "A bOOk"},
  { "SiP  ", "tEA   "},
  { "EAt  ", "hEArt "},
  { "LEtit", "riP   "},
  { "Putit", "nEAr  "},
  { "DiP A", "tOE in"},
  { "DON'T", "PANiC "},
  { "SEi  ", "fESCH "},
  { "SEi  ", "bESSEr"},
  { "SEi  ", "LEiCht"},
  { "SEi  ", "innEn "},
  { "SEi  ", "bEGAbt"},
  { "SEi  ", "biSSIg"},
  { "SEi  ", "FALtIg"},
  { "SEi  ", "gEFEIt"},
  { "gEh  ", "rAUS  "},
  { "gIb  ", "ACht  "},
  { "hoL  ", "HiLFE "},
  { "     ", "bLUFFE"},
  { "     ", "dArbE "},
  { "     ", "fASELE"},
  { "     ", "hirnE "},
  { "     ", "JubLE "},
  { "     ", "grInSE"},
  { "     ", "LAndE "},
  { "     ", "LAUErE"},
  { "     ", "LObE  "},
  { "     ", "nArrE "},
  { "     ", "OrdnE "},
  { "     ", "PFEIFE"},
  { "     ", "PInSLE"},
  { "     ", "PLOPPE"},
  { "     ", "PLottE"},
  { "     ", "PrAhLE"},
  { "     ", "rAUnE "},
  { "     ", "rAtE  "},
  { "     ", "rEdE  "},
  { "     ", "rEttE "},
  { "     ", "SEndE "},
  { "     ", "SPiELE"},
  { "     ", "SPinnE"},
  { "     ", "StAPLE"},
  { "     ", "StAUnE"},
  { "     ", "tEStE "},
  { "     ", "dEUtE "},
  { "     ", "dULdE "},
  { "     ", "ruhE  "},
  { "AUF  ", "PUdLE "},
  { "SEi  ", "PLEItE"},
  { "SEi  ", "gLEICH"},
  { "Er   ", "nEnnE "},
  { "dIE  ", "ChAnCE"},
  { "hAU  ", "drAUF "},
  { "ISS  ", "APFEL "},
  { "ISS  ", "hIrSE "},
  { "     ", "hUpE  "},
  { "     ", "hUpE  "},
  { "ISS  ", "bIttEr"},
  { "ISS  ", "buntEr"},
  { "nUr  ", "gELd  "},
  { "rUF  ", "An    "},
  { "tu   ", "niChTS"},
  { "ruh  ", "AUS   "},
  { "SAg  ", "nEiN  "},
  { "SAg  ", "JA    "},
  { "SAg  ", "Ab    "},
  { "SAg  ", "nichTS"},
  { "hAb  ", "Ahnung"},
  { "hAb  ", "gEnUg "},
  { "hEb  ", "Ab    "},
  { "lEg  ", "AuF   "},
  { "LEb  ", "LAUt  "},
  { "trY  ", "hArd  "},
  { "gEtUP", "      "},
  { "CUtUP", "ShOrt "},
  { "PUtOn", "hOLd  "},
  { "ACtOn", "CUE   "},
  { "dIGUp", "trUtH "},
  { "acton", "PLAn  "},
  { "LAYUP", "hOPE  "},
  { "PUtUP", "FIGht "},
  { "SEtOn", "PATh  "},
  { "PutIn", "PLACE "},
  { "TrYOn", "ShOES "},
  { "LAYAn", "Egg   "},
  { "USE  ", "hEAd  "},
  { "Runin", "CirCLE"},
  { "GEtUP", "SPEEd "},
  { "GEtOn", "bOArd "},
  { "LAYOn", "bEd   "},
  { "GEtin", "CAr   "},
  { "EAt  ", "Up    "},
  { "bIdOn", "Art   "},
  { "PUtOn", "bLASt "},
  { "Runto", "GroUnd"},
  { "RunUP", "A hiLL"},
  { "SAYHi", "Say HO"},
  { "CUt  ", "COrNer"},
  { "PUttO", "USE   "},
  { "Runon", "hOPE  "},
  { "COP  ", "OUt   "},
  { "trYtO", "LAUGh "},
  { "get  ", "A GrIP"},
  { "CUt A", "dEAL  "},
  { "CUt A", "pATh  "},
  { "SET  ", "pACE  "},
  { "bE   ", "tHerE "},
  { "Run  ", "AFOUL "},
  { "PutOn", "HAt   "},
  { "PEE  ", "OFtEn "},
  { "GO   ", "UP    "},
  { "SEt  ", "SAiL  "},
  { "GO tO", "Light "},
  { "GEt  ", "SLEEP "},
  { "bE   ", "reAdy "},
  { "dOn't", "bItE  "},
  { "dOn't", "pAy   "},
  { "dOn't", "rEpLy "},
  { "     ", "stAy  "},
  { "dOn't", "stop  "},
  { "dOn't", "go    "},
  { "sit  ", "stiLL "},
  { "     ", "rest  "},
  { "     ", "deny  "},
  { "     ", "plan  "},
  { "LiEbE", "dich  "},
  { "gib  ", "sAURES"},
  { "SEtOn", "HOLd  "},
  { "tOUCH", "grASS "},
  { "useit", "up    "},
  { "fly  ", "high  "},
  { "bid  ", "higH  "},
  { "push ", "hArd  "},
  { "dig  ", "hOLE  "},
  { "pULL ", "FEEt  "},
  { "fLiP ", "COin  "},
  { "PAint", "Sign  "},
  { "LiFt ", "PEn   "},
  { "JOin ", "CLUb  "},
  { "PAint", "Sign  "},
  { "PEt A", "CAt   "},
  { "SitOn", "rUg   "},
  { "nod  ", "YES   "},
  { "CAtCh", "UP    "},
  { "SLidE", "in    "},
  { "RiSE ", "high  "},
  { "bE   ", "StrOng"},
  { "BUy  ", "StUFF "},
  { "gO   ", "FAST  "},
  { "SEt A", "gOAL  "},
  { "dOn't", "bOthEr"},
  { "     ", "FOrgEt"},
  { "FACE ", "FEAr  "},
  { "CLAP ", "ALOnG "},
  { "FLIP ", "SCriPt"},
  { "SPit ", "FirE  "},
  { "hit  ", "FLOOr "},
  { "COPY ", "STYLE "},
  { "tUrn ", "EYES  "},
  { "     ", "PAUSE "},
  { "     ", "LiSTEn"},
  { "CALL ", "Out   "},
  { "StAY ", "OUt   "},
  { "FEEd ", "bird  "},
  { "SmELL", "bLOOd "},
  { "tOUCh", "bASE "},
  { "rEACh", "OUt   "},
  { "gO   ", "OUt   "},
  { "tUrn ", "it OFF"},
  { "EAt A", "bUg   "},
  { "digit", "      "},
  { "CLOSE", "EArS  "},
  { "dO it", "ALOnE "},
  { "STAY ", "SOFt  "},
  { "TOO  ", "SOOn  "},
  { "GEt  ", "hArd  "},
  { "FEEL ", "FrEE  "},
  { "BE IN", "PEACE "},
  { "ASK 4", "LESS  "},
  { "DOthE", "DAnCE "},
  { "ASK 4", "ChAngE"},
  { "PAYUP", "Front "},
  { "CLOSE", "DEAL  "},
  { "hop  ", "on    "},
  { "gEtin", "trAncE"},
  { "bE   ", "POLiTE"},
  { "Get  ", "LOSt  "},
  { "POSt ", "BLOg  "},
  { "bE   ", "PrOUd "},
  { "gEt  ", "dirty "},
  { "fEEL ", "LEGS  "},
  { " stay", "COOL  "},
  { "stArt", "tEST  "},
  { "EAt  ", "FiSH  "},
  { "go   ", "onLinE"},
  { "DiAL ", "iN    "},
  { "gEt  ", "CLOSE "},
  { "     ", "rESiST"},
  { "     ", "PUnCH "},
  { "CUt  ", "LOOSE "},
  { "     ", "PUSH  "},
  { "     ", "PULL  "},
  { "     ", "HEAL  "},
  { "     ", "bATHE "},
  { "     ", "ChAT  "},
  { "bE   ", "PrOUd "},
  { "CArE ", "LESS  "},
  { "CALL ", "hEr   "},
  { "ChEEr", "up    "},
  { "ClEAn", "up    "},
  { "EArn ", "it    "},
  { "Enter", "CAgE  "},
  { "     ", "FLOAt "},
  { "don't", "FOLd  "},
  { "USE  ", "FOrCE "},
  { "     ", "grASP "},
  { "     ", "grind "},
  { "don't", "hAtE  "},
  { "     ", "JiggLE"},
  { "LiFt ", "OFF   "},
  { "Find ", "nEEd  "},
  { "OFFEr", "hELp  "},
  { "rEAd ", "Print "},
  { "PLAY ", "rECORd"},
  { "     ", "rEdUCE"},
  { "     ", "rEFUSE"},
  { "     ", "rEPAir"},
  { "StAnd", "tALL  "},
  { "     ", "tEACh "},
  { "tele ", "typE  "},
  { "tap  ", "dAnCE "},
  { "     ", "tAStE "},
  { "     ", "tEASE "},
  { "     ", "unite "},
  { "   un", "LEASH "},
  { "     ", "USURP "},
  { "     ", "YEArn "},
  { "     ", "APPLY "},
  { "     ", "ASSISt"},
  { "     ", "bEgin "},
  { "     ", "bELOnG"},
  { "     ", "bOASt "},
  { "CLOSE", "LAPtOP"},
  { "Add  ", "LESS  "},
  { "     ", "AdAPt "},
  { "     ", "rAnt  "},
  { "     ", "rECALL"},
  { "fACE ", "it    "},
  { "ALter", "sTATE "},
  { "fade ", "in    "},
  { "     ", "reel  "},
  { "     ", "fill  "},
  { "     ", "ArguE "},
  { "Arm  ", "rACE  "},
  { "     ", "redo  "},
  { "     ", "undo  "},
  { "     ", "copy  "},
  { "     ", "Audit "},
  { "     ", "rEsEnt"},
  { "baLE ", "OUt   "},
  { "SEnd ", "giFt  "},
  { "bAt  ", "EYE   "},
  { "FEEL ", "hEAt  "},
  { "gEt  ", "bOOSt "},
  { "gEt  ", "hint  "},
  { "     ", "bUrP  "},
  { "gO tO", "StOrE "},
  { "bE   ", "PrOUd "},
  { "bE   ", "PrOUd "},
  { "bE   ", "PrOUd "},
  { "bE   ", "PrOUd "},
  { "bE   ", "PrOUd "},
  { "bE   ", "PrOUd "},
  { "bE   ", "PrOUd "},
  { "bE   ", "PrOUd "},
  { "bE   ", "PrOUd "},
  { "bE   ", "PrOUd "},
  { "bE   ", "PrOUd "},
  { "bE   ", "PrOUd "},
  { "bE   ", "PrOUd "},
  { "bE   ", "PrOUd "},
  { "bE   ", "PrOUd "},
  { "bE   ", "PrOUd "},
  { "bE   ", "PrOUd "},
  { "bE   ", "PrOUd "},
  { "bE   ", "PrOUd "},
  { "bE   ", "PrOUd "},
  { "bE   ", "PrOUd "},
  { "bE   ", "PrOUd "},
  { "bE   ", "PrOUd "},
  { "bE   ", "PrOUd "},
  { "bE   ", "PrOUd "},
  { "bE   ", "PrOUd "},
  { "bE   ", "PrOUd "},
  { "bE   ", "PrOUd "},
  { "bE   ", "PrOUd "},
  { "bE   ", "PrOUd "},
  { "bE   ", "PrOUd "},
  { "bE   ", "PrOUd "},
  { "bE   ", "PrOUd "},
  { "bE   ", "PrOUd "},
  { "bE   ", "PrOUd "},
  { "bE   ", "PrOUd "},
  { "bE   ", "PrOUd "},
  { "bE   ", "PrOUd "},
  { "bE   ", "PrOUd "},
  { "bE   ", "PrOUd "},
  { "OPt  ", "OUt   "}
};
