/*
 * MIT License
 *
 * Copyright (c) 2025 <#author_name#>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#pragma once

#include "movement.h"

/*
 * A DESCRIPTION OF YOUR WATCH FACE
 *
 * and a description of how use it
 *
 */

typedef struct {
    // Anything you need to keep track of, put it here!
    uint8_t unused;
    unsigned int counter;
} wordoftheday_state_t;

void wordoftheday_face_setup(uint8_t watch_face_index, void ** context_ptr);
void wordoftheday_face_activate(void *context);
bool wordoftheday_face_loop(movement_event_t event, void *context);
void wordoftheday_face_resign(void *context);

#define wordoftheday_face ((const watch_face_t){ \
    wordoftheday_face_setup, \
    wordoftheday_face_activate, \
    wordoftheday_face_loop, \
    wordoftheday_face_resign, \
    NULL, \
})

static const char words[][6][7] = {
  { "SPILL", "tEA   "},
  { "EAt  ", "hEArt "},
  { "LEtit", "riP   "},
  { "Putit", "nEAr  "},
  { "DiP A", "tOE in"},
  { "SEi  ", "biSSIg"},
  { "gIb  ", "ACht  "},
  { "hoL  ", "HiLFE "},
  { "     ", "PrAhLE"},
  { "SEnDE", "GELd  "},
  { "dEUte", "ANDERS"},
  { "dULdE", "niCHtS"},
  { "SEi  ", "PLEItE"},
  { "grEiF", "ChAnCE"},
  { "hAU  ", "drAUF "},
  { "ISS  ", "bIttEr"},
  { "rUF  ", "An    "},
  { "tu   ", "niChTS"},
  { "close", "loop  "},
  { "SAg  ", "nEiN  "},
  { "SAg  ", "JA    "},
  { "SAg  ", "Ab    "},
  { "SAg  ", "nichTS"},
  { "hAb  ", "Ahnung"},
  { "hAb  ", "gEnUg "},
  { "hEb  ", "Ab    "},
  { "lEg  ", "AuF   "},
  { "LEb  ", "LAUt  "},
  { "trY  ", "hArd  "},
  { "gEtUP", "      "},
  { "CUtUP", "ShOrt "},
  { "PUtOn", "hOLd  "},
  { "ACtOn", "CUE   "},
  { "dIGUp", "trUtH "},
  { "acton", "PLAn  "},
  { "LAYUP", "hOPE  "},
  { "PUtUP", "FIGht "},
  { "SEtOn", "PATh  "},
  { "PutIn", "PLACE "},
  { "TrYOn", "ShOES "},
  { "LAYAn", "Egg   "},
  { "USE  ", "hEAd  "},
  { "Runin", "CirCLE"},
  { "GEtUP", "SPEEd "},
  { "GEtOn", "bOArd "},
  { "LAYOn", "bEd   "},
  { "GEtin", "CAr   "},
  { "EAt  ", "Up    "},
  { "bIdOn", "Art   "},
  { "PUtOn", "bLASt "},
  { "Runto", "GroUnd"},
  { "RunUP", "A hiLL"},
  { "SAYHi", "Say HO"},
  { "CUt  ", "COrNer"},
  { "PUttO", "USE   "},
  { "Runon", "hOPE  "},
  { "COP  ", "OUt   "},
  { "   bE", "AbSEnT"},
  { "trYtO", "LAUGh "},
  { "get a", "GrIP  "},
  { "CUt A", "dEAL  "},
  { "CUt A", "pATh  "},
  { "SET  ", "pACE  "},
  { "bE   ", "tHerE "},
  { "Run  ", "AFOUL "},
  { "PutOn", "HAt   "},
  { "PEE  ", "OFtEn "},
  { "GO   ", "UP    "},
  { "SEt  ", "SAiL  "},
  { "GO tO", "SOURCE"},
  { "GEt  ", "SLEEP "},
  { "bE   ", "reAdy "},
  { "dOn't", "bItE  "},
  { "dOn't", "pAy   "},
  { "dOn't", "rEpLy "},
  { "stAy ", "here  "},
  { "dOn't", "stop  "},
  { "dOn't", "go    "},
  { "sit  ", "stiLL "},
  { "     ", "rest  "},
  { "     ", "deny  "},
  { "     ", "plan  "},
  { "LiEbE", "dich  "},
  { "gib  ", "sAURES"},
  { "tOUCH", "grASS "},
  { "useit", "up    "},
  { "fly  ", "high  "},
  { "bid  ", "higH  "},
  { "push ", "hArd  "},
  { "dig  ", "hOLE  "},
  { "pULL ", "FEEt  "},
  { "fLiP ", "COin  "},
  { "CRY  ", "LOUD  "},
  { "PAint", "Sign  "},
  { "LiFt ", "PEn   "},
  { "JOin ", "CLUb  "},
  { "PEt A", "CAt   "},
  { "SitOn", "rUg   "},
  { "nod  ", "YES   "},
  { "CAtCh", "UP    "},
  { "SLidE", "in    "},
  { "RiSE ", "high  "},
  { "bE   ", "StrOng"},
  { "BUy  ", "StUFF "},
  { "gO   ", "FAST  "},
  { "SEt A", "gOAL  "},
  { "dOn't", "bOthEr"},
  { "     ", "FOrgEt"},
  { "FACE ", "FEAr  "},
  { "CLAP ", "ALOnG "},
  { "FLIP ", "SCriPt"},
  { "SPit ", "FirE  "},
  { "hit  ", "FLOOr "},
  { "COPY ", "STYLE "},
  { "tUrn ", "EYES  "},
  { "PAUSE", "OFtEn "},
  { "     ", "LiSTEn"},
  { "CALL ", "Out   "},
  { "StAY ", "OUt   "},
  { "FEEd ", "bird  "},
  { "REAd ", "A bOOk"},
  { "SmELL", "bLOOd "},
  { "tOUCh", "bASE "},
  { "rEACh", "OUt   "},
  { "gO   ", "OUt   "},
  { "tUrn ", "it OFF"},
  { "EAt A", "bUg   "},
  { "digit", "      "},
  { "CLOSE", "EArS  "},
  { "dO it", "ALOnE "},
  { "STAY ", "SOFt  "},
  { "TOO  ", "SOOn  "},
  { "GEt  ", "hArd  "},
  { "FEEL ", "FrEE  "},
  { "Find ", "PEACE "},
  { "ASK 4", "LESS  "},
  { "DOthE", "DAnCE "},
  { "ASK 4", "ChAngE"},
  { "PAYUP", "Front "},
  { "CLOSE", "DEAL  "},
  { "hop  ", "on    "},
  { "gEtin", "trAncE"},
  { "bE   ", "POLiTE"},
  { "Get  ", "LOSt  "},
  { "POSt ", "BLOg  "},
  { "bE   ", "PrOUd "},
  { "gEt  ", "dirty "},
  { "fEEL ", "LEGS  "},
  { " stay", "COOL  "},
  { "stArt", "tEST  "},
  { "EAt  ", "FiSH  "},
  { "go   ", "onLinE"},
  { "DiAL ", "iN    "},
  { "gEt  ", "CLOSE "},
  { "     ", "rESiST"},
  { "     ", "PUnCH "},
  { "CUt  ", "LOOSE "},
  { "     ", "PUSH  "},
  { "     ", "PULL  "},
  { "     ", "HEAL  "},
  { "     ", "bATHE "},
  { "     ", "ChAT  "},
  { "bE   ", "PrOUd "},
  { "CArE ", "LESS  "},
  { "CALL ", "hEr   "},
  { "ChEEr", "up    "},
  { "ClEAn", "up    "},
  { "EArn ", "it    "},
  { "Enter", "CAgE  "},
  { "     ", "FLOAt "},
  { "don't", "FOLd  "},
  { "USE  ", "FOrCE "},
  { "     ", "grASP "},
  { "     ", "grind "},
  { "don't", "hAtE  "},
  { "     ", "JiggLE"},
  { "LiFt ", "OFF   "},
  { "Find ", "nEEd  "},
  { "OFFEr", "hELp  "},
  { "rEAd ", "Print "},
  { "PLAY ", "rECORd"},
  { "     ", "rEdUCE"},
  { "     ", "rEFUSE"},
  { "     ", "rEPAir"},
  { "StAnd", "tALL  "},
  { "     ", "tEACh "},
  { "tele ", "typE  "},
  { "tap  ", "dAnCE "},
  { "     ", "tAStE "},
  { "     ", "tEASE "},
  { "     ", "unite "},
  { "   un", "LEASH "},
  { "     ", "USURP "},
  { "     ", "YEArn "},
  { "     ", "APPLY "},
  { "     ", "ASSISt"},
  { "bEgin", "LATE  "},
  { "     ", "bELOnG"},
  { "     ", "bOASt "},
  { "CLOSE", "LAPtOP"},
  { "Add  ", "LESS  "},
  { "     ", "AdAPt "},
  { "     ", "rAnt  "},
  { "     ", "rECALL"},
  { "LOOSE", "FACE  "},
  { "ALter", "sTATE "},
  { "fade ", "in    "},
  { "     ", "reel  "},
  { "pass ", "note  "},
  { "don't", "argue "},
  { "Arm  ", "rACE  "},
  { "     ", "redo  "},
  { "     ", "undo  "},
  { "     ", "copy  "},
  { "     ", "Audit "},
  { "     ", "rEsEnt"},
  { "baLE ", "OUt   "},
  { "SEnd ", "giFt  "},
  { "bAt  ", "EYE   "},
  { "FEEL ", "hEAt  "},
  { "gEt  ", "bOOSt "},
  { "gEt  ", "hint  "},
  { "     ", "bUrP  "},
  { "gO tO", "StOrE "},
  { "bEAt ", "it    "},
  { "   un", "lEArn "},
  { "liebe", "dIch  "},
  { "SpiLL", "bEAnS "},
  { "add  ", "SALt  "},
  { "don't", "ChAnge"},
  { "grEAt", "idEA  "},
  { "     ", "bLUSh "},
  { "     ", "CuddLE"},
  { "SAY  ", "ChEESE"},
  { "bE   ", "PrOUd "},
  { "trUSt", "bUSK  "},
  { "hold ", "FirE  "},
  { "FEEL ", "JOY   "},
  { "StIr ", "UP    "},
  { "SEtin", "Stone "},
  { "try'n", "error "},
  { "come ", "and go"},
  { "     ", "hide  "},
  { "CAll ", "gobLin"},
  { "go to", "SPaCe "},
  { "rEACH", "beyond"},
  { "quit ", "dayjob"},
  { "stop ", "early "},
  { "Sally", "Forth "},
  { "     ", "yearn "},
  { "     ", "TiLT  "},
  { "enter", "orbit "},
  { "     ", "Leach "},
  { "trans", "greSS "},
  { "riSE ", "ShinE "},
  { "frag ", "nach  "},
  { "phone", "friend"},
  { "CALL ", "DOC   "},
  { "Send ", "SPRAY "},
  { "Shoot", "at Sun"},
  { "hide ", "anger "},
  { "punch", "up    "},
  { "burst", "PrOUd "},
  { "eLude", "PrOUd "},
  { "bust ", "open  "},
  { "grASP", "      "},
  { "haunt", "PrOUd "},
  { "jolt ", "PrOUd "},
  { "soar ", "aLone "},
  { "spit ", "PrOUd "},
  { "split", "banana"},
  { "SteaL", "nOSe  "},
  { "CrASH", "PArty "},
  { "StAy ", "ALErt "},
  { "bE to", "gether"},
  { "eat  ", "rich  "},
  { "get  ", "going "},
  { "eat a", "bug   "},
  { "     ", "rescue"},
  { "get  ", "bonuS "},
  { "cutit", "out   "},
  { "sign ", "up    "},
  { "force", "deal  "},
  { "sort ", "stuFF "},
  { "don't", "streSS"},
  { "tell ", "tale  "},
  { "pile ", "up    "},
  { "you  ", "RULE  "},
  { "hunt ", "      "},
  { "learn", "quote "},
  { "seeit", "first "},
  { "ring ", "bell  "},
  { "net  ", "out   "},
  { "puton", "pile  "},
  { "out  ", "source"},
  { "chase", "nIght" },
  { "find ", "haven "},
  { "open ", "gate  "},
  { "raise", "hell  "},
  { "SpiLL", "facts "},
  { "shed ", "tearS "},
  { "tell ", "Noone "},
  { "trade", "blood "},
  { "defy ", "fate  "},
  { "play ", "dead  "},
  { "offer", "less  "},
  { "feed ", "rage  "},
  { "feed ", "SOUL  "},
  { "hide ", "SECRET"},
  { "lift ", "CURSE "},
  { "tell ", "STORY "},
  { "plant", "seed  "},
  { "spin ", "a tale"},
  { "hit  ", "target"},
  { "paint", "lines "},
  { "find ", "friend"},
  { "loose", "happy "},
  { "catch", "air   "},
  { "try  ", "again "},
  { "quit ", "early "},
  { "   un", "seat  "},
  { "     ", "untie "},
  { "     ", "PrOUd "},
  { " face", "it all"},
  { " burn", "it    "},
  { "   en", "snare "},
  { "     ", "jolt  "},
  { "     ", "bedew "},
  { "train", "eye   "},
  { "cast ", "speLL "},
  { "   re", "nounce"},
  { "bite ", "bullet"},
  { " hit ", "road  "},
  { "bite ", "lip   "},
  { "lay a", "trap  "},
  { "beat ", "a path"},
  { "light", "candle"},
  { "get a", "clue  "},
  { "stare", "abyss "},
  { "comb ", "hair  "},
  { "catch", "breath"},
  { "join ", "fray  "},
  { "fill ", "void  "},
  { "forge", "PATH  "},
  { "bEnd ", "RULES "},
  { "hold ", "line  "},
  { "     ", "ORACLE"},
  { "reap ", "CHAOS "},
  { "bend ", "line  "},
  { "trace", "path  "},
  { "turn ", "page  "},
  { "cut  ", "ties  "},
  { "Flip ", "table "},
  { "lift ", "spirit"},
  { "ride ", "tide  "},
  { "hit  ", "roof  "},
  { "cast ", "net   "},
  { "   de", "scend "},
  { "bEat ", "buSh  "},
  { "spice", "up    "},
  { "play ", "cards "},
  { "turn ", "tables"},
  { "chase", "tail  "},
  { "hit  ", "nail  "},
  { "bE   ", "PrOUd "},
  { "OPt  ", "OUt   "}
};
