/*
 * MIT License
 *
 * Copyright (c) 2025 <#author_name#>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#pragma once

#include "movement.h"

/*
 * A DESCRIPTION OF YOUR WATCH FACE
 *
 * and a description of how use it
 *
 */

typedef struct {
    // Anything you need to keep track of, put it here!
    uint8_t unused;
    unsigned int counter;
} wordoftheday_state_t;

void wordoftheday_face_setup(uint8_t watch_face_index, void ** context_ptr);
void wordoftheday_face_activate(void *context);
bool wordoftheday_face_loop(movement_event_t event, void *context);
void wordoftheday_face_resign(void *context);

#define wordoftheday_face ((const watch_face_t){ \
    wordoftheday_face_setup, \
    wordoftheday_face_activate, \
    wordoftheday_face_loop, \
    wordoftheday_face_resign, \
    NULL, \
})

static const char words[][6][7] = {
  { "SPILL", "tea   "},
  { "eat  ", "heart "},
  { "Putit", "near  "},
  { "close", "Loop  "},
  { "hold ", "tongue"},
  { "drink", "JUICE "},
  { "catch", "Air   "},
  { "LiEbE", "dich  "},
  { "taste", "bittEr"},
  { "tu   ", "nichTS"},
  { "Sag  ", "NEiN  "},
  { "Sag  ", "NichTS"},
  { "gib  ", "SaureS"},
  { "SCHAU", "GENAU "},
  { "heb  ", "ab    "},
  { "hab  ", "genug "},
  { "Leg  ", "auF   "},
  { "hoL  ", "HiLFE "},
  { "RUF  ", "AN    "},
  { "Sag  ", "Ab    "},
  { "hau  ", "drAUF "},
  { "tritt", "arsch "},
  { "Sei  ", "AndeRS"},
  { "Gib  ", "Acht  "},
  { "grEiF", "ChanCE"},
  { "duLde", "NichTS"},
  { "trY  ", "hard  "},
  { "USE  ", "hEAd  "},
  { "gEtUP", "earLy "},
  { "riSe ", "Shine "},
  { "CUtUP", "Short "},
  { "PUtOn", "HOLd  "},
  { "ActOn", "CUE   "},
  { "dIGUp", "truth "},
  { "actOn", "PLAn  "},
  { "LAYUP", "hOPE  "},
  { "PUtUP", "FiGht "},
  { "SetOn", "PATh  "},
  { "Putin", "PLACE "},
  { "TrYOn", "ShoeS "},
  { "LAYAn", "EGG   "},
  { "Runin", "CircLE"},
  { "GEtUP", "SPEEd "},
  { "GEtOn", "board "},
  { "LAYOn", "bed   "},
  { "GEtin", "CAr   "},
  { "bidOn", "Art   "},
  { "PUtOn", "bLASt "},
  { "Runto", "Ground"},
  { "SAYHi", "Say HO"},
  { "PUttO", "USE   "},
  { "trYtO", "LAUGh "},
  { "CUt A", "pATh  "},
  { "PutOn", "HAt   "},
  { "push ", "hard  "},
  { "GEt  ", "SLEEP "},
  { "EAt  ", "Up    "},
  { "gO   ", "FAST  "},
  { "PEE  ", "OFtEn "},
  { "SET  ", "pACE  "},
  { "don't", "stop  "},
  { "Set  ", "SaiL  "},
  { "RunUP", "A hiLL"},
  { "Cut  ", "Corner"},
  { "COP  ", "OUt   "},
  { "GO tO", "SourCe"},
  { "be   ", "ready "},
  { "be   ", "there "},
  { "bid  ", "HiGH  "},
  { "chase", "taiL  "},
  { "dOn't", "pay   "},
  { "dOn't", "repLy "},
  { "Lay  ", "  down"},
  { "   bE", "AbSEnT"},
  { "GO   ", "UP    "},
  { "sit  ", "stiLL "},
  { "tOUCH", "GrASS "},
  { "FEEd ", "bird  "},
  { "fEEL ", "LEGS  "},
  { "Find ", "PEACE "},
  { "CUt  ", "LOOSE "},
  { "Set A", "GOAL  "},
  { "plan ", "ahead "},
  { "fLiP ", "Coin  "},
  { "get a", "GriP  "},
  { "nod  ", "YES   "},
  { "CUt A", "dEAL  "},
  { "RunOn", "hOPE  "},
  { "Run  ", "AFOUL "},
  { "Useit", "Up    "},
  { "dOn't", "bitE  "},
  { "stAy ", "here  "},
  { "     ", "rest  "},
  { "     ", "deny  "},
  { "don't", "bothEr"},
  { "don't", "GO    "},
  { "LiFt ", "Pen   "},
  { "FLy  ", "HiGh  "},
  { "Catch", "UP    "},
  { "Join ", "CLUb  "},
  { "pLAy ", "ALONG "},
  { "bend ", "RuLES "},
  { "SAY  ", "ChEESE"},
  { "gEt  ", "dirty "},
  { "dig  ", "hoLe  "},
  { "Sitin", "hoLe  "},
  { "CLOSE", "LAPtOP"},
  { "doge ", "bullet"},
  { "pULL ", "FEEt  "},
  { "Paint", "Sign  "},
  { "PEt A", "CAt   "},
  { "RiSE ", "High  "},
  { "CRY  ", "LOUd  "},
  { "bE   ", "Strong"},
  { "HOLd ", "Ground"},
  { "StAnd", "tALL  "},
  { "     ", "Forget"},
  { "FACE ", "FEAr  "},
  { "CLAP ", "ALonG "},
  { "enter", "ChAT  "},
  { "SLidE", "in    "},
  { "SPit ", "Fire  "},
  { "Enter", "CAGE  "},
  { "hit  ", "FLOOr "},
  { "tUrn ", "EYES  "},
  { "gEt  ", "hint  "},
  { "COPY ", "STYLE "},
  { "don't", "LiSTEN"},
  { "StAY ", "OUt   "},
  { "REAd ", "ThiS  "},
  { "CALL ", "OUt   "},
  { "GEt  ", "hArd  "},
  { "SmELL", "bLood "},
  { "FEEL ", "HEAt  "},
  { "tOUCh", "bASE "},
  { "GO   ", "OUt   "},
  { "FLIP ", "ScriPt"},
  { "PUNCH", "UP    "},
  { "dO it", "ALONE "},
  { "CLOSE", "EArS  "},
  { "Get  ", "LOSt  "},
  { "turn ", "it OFF"},
  { "EAt A", "bUG   "},
  { "get  ", "bonuS "},
  { "don't", "hAtE  "},
  { "OFFEr", "heLp  "},
  { "STAY ", "SOFt  "},
  { "FEEL ", "Free  "},
  { "TOO  ", "SOON  "},
  { "run  ", "errAnd"},
  { "     ", "ChAnGE"},
  { "Offer", "LESS  "},
  { "CLOSE", "dEAL  "},
  { "PAYUP", "Front "},
  { "hop  ", "on    "},
  { "gEtin", "trAncE"},
  { "ALter", "sTATE "},
  { "POSt ", "bLog  "},
  { " stay", "COOL  "},
  { "stArt", "tEST  "},
  { "catch", "FiSH  "},
  { "go   ", "onLinE"},
  { "DiAL ", "in    "},
  { "gEt  ", "CLOSE "},
  { "bE   ", "Proud "},
  { "     ", "PUSH  "},
  { "     ", "PULL  "},
  { "     ", "bLUSh "},
  { "burst", "      "},
  { "gEt  ", "bOOSt "},
  { "     ", "JiggLE"},
  { "jolt ", "      "},
  { "     ", "reSiST"},
  { "     ", "tAStE "},
  { "     ", "teASE "},
  { "     ", "bATHE "},
  { "     ", "HEAL  "},
  { "     ", "rEdUCE"},
  { "     ", "rEFUSE"},
  { "     ", "rEPAir"},
  { "hide ", "anger "},
  { "bE   ", "strict"},
  { "CArE ", "LESS  "},
  { "ChEEr", "Up    "},
  { "CALL ", "her   "},
  { "be   ", "POLiTE"},
  { "SpiLL", "beanS "},
  { "SitOn", "rug   "},
  { "     ", "FLOAt "},
  { "don't", "FoLd  "},
  { "grASP", "hand  "},
  { "     ", "grind "},
  { "     ", "rAnt  "},
  { "JOIn ", "dANCE "},
  { "LiFt ", "oFF   "},
  { "Find ", "need  "},
  { "rEAd ", "Print "},
  { "PLAY ", "rECORd"},
  { "     ", "tEACh "},
  { "tele ", "typE  "},
  { "tap  ", "dAncE "},
  { "     ", "unite "},
  { "   un", "LEASH "},
  { "     ", "USURP "},
  { "     ", "YeArn "},
  { "     ", "APPLY "},
  { "     ", "ASSiSt"},
  { "chase", "Night "},
  { "Stay ", "LATE  "},
  { "don't", "bELOnG"},
  { "     ", "bOASt "},
  { "Add  ", "LESS  "},
  { "     ", "AdAPt "},
  { "   UN", "LEArn "},
  { "sort ", "stuFF "},
  { "teLL ", "apart "},
  { "   de", "brief "},
  { "     ", "rECALL"},
  { "   un", "delete"},
  { "LOOSE", "FACE  "},
  { "SALLy", "Forth "},
  { "add  ", "SALt  "},
  { "fade ", "in    "},
  { "ClEAn", "Up    "},
  { "SEnd ", "giFt  "},
  { "     ", "reeL  "},
  { "pass ", "note  "},
  { "don't", "argue "},
  { "Arm  ", "race  "},
  { "     ", "redo  "},
  { "     ", "undo  "},
  { "     ", "Audit "},
  { "   un", "seat  "},
  { "     ", "rEsEnt"},
  { "baLE ", "OUt   "},
  { "bAt  ", "EYE   "},
  { "dig  ", "it out"},
  { " burn", "it    "},
  { "PAUSE", "OFtEN "},
  { "come ", "and go"},
  { "     ", "bUrP  "},
  { "gO tO", "StOrE "},
  { "LOOSE", "note  "},
  { "BUy  ", "StuFF "},
  { "bEAt ", "it    "},
  { "bury ", "past  "},
  { "great", "ideA  "},
  { "     ", "CuddLE"},
  { "StIr ", "uP    "},
  { "SEtin", "Stone "},
  { "try'n", "error "},
  { "USE  ", "FOrCE "},
  { "CALL ", "gobLin"},
  { "stop ", "early "},
  { "quit ", "dayjob"},
  { "trUSt", "bUSK  "},
  { "Shoot", "at Sun"},
  { "hold ", "FirE  "},
  { "go to", "SPaCe "},
  { "enter", "orbit "},
  { "rEACH", "beyond"},
  { "trans", "greSS "},
  { "     ", "yearn "},
  { "     ", "TiLT  "},
  { "grASP", "      "},
  { "     ", "hide  "},
  { "     ", "rescue"},
  { "     ", "Leach "},
  { "stare", "abyss "},
  { "phone", "friend"},
  { " hoLd", "LiNe  "},
  { "Send ", "SPRAY "},
  { "frag ", "nach  "},
  { "CaLL ", "dOC   "},
  { "eLude", "      "},
  { "bust ", "open  "},
  { "haunt", "house "},
  { "soar ", "aLone "},
  { "hold ", "hand  "},
  { "EArn ", "it    "},
  { "spLit", "baNaNa"},
  { "SteaL", "NOSe  "},
  { "StAy ", "ALert "},
  { "bE to", "gether"},
  { "eat  ", "rich  "},
  { "get  ", "goiNg "},
  { "split", "hair  "},
  { "CrASH", "Party "},
  { "cutit", "out   "},
  { "siGN ", "Up    "},
  { "shift", "gear  "},
  { "teLL ", "STORY "},
  { "defy ", "fate  "},
  { "don't", "streSS"},
  { "piLe ", "Up    "},
  { "hunt ", "      "},
  { "Learn", "qUOtE "},
  { "seeit", "FirSt "},
  { "ring ", "beLL  "},
  { "net  ", "OUT   "},
  { "putOn", "piLe  "},
  { "OUt  ", "sourCE"},
  { "OpeN ", "gate  "},
  { "raise", "hell  "},
  { " face", "facts "},
  { "shed ", "tearS "},
  { "tell ", "NOone "},
  { "trade", "bLOOd "},
  { "rEACH", "OUt   "},
  { "fEEd ", "ragE  "},
  { "feed ", "SOUL  "},
  { "hide ", "SECRET"},
  { "Lift ", "CURSE "},
  { "pLant", "seed  "},
  { "spin ", "a tAle"},
  { "cast ", "speLL "},
  { "name ", "quest "},
  { "find ", "friend"},
  { "paiNt", "LiNEs "},
  { "FEEL ", "JOY   "},
  { "happy", "happy "},
  { "try  ", "again "},
  { "quit ", "SOON  "},
  { "tiny ", "StepS "},
  { "     ", "UNtiE "},
  { "hit  ", "target"},
  { "FLIP ", "FLOP  "},
  { "   en", "snare "},
  { "     ", "jolt  "},
  { "     ", "bedew "},
  { "train", "eye   "},
  { "   re", "nounce"},
  { " hit ", "ROAd  "},
  { "bite ", "Lip   "},
  { " faCE", "it ALL"},
  { "get a", "cLUe  "},
  { "Lay a", "trap  "},
  { "beat ", "a path"},
  { "Light", "CandLe"},
  { "comb ", "hair  "},
  { "Catch", "breath"},
  { "join ", "fray  "},
  { "fiLL ", "void  "},
  { "forGE", "PATh  "},
  { "turn ", "PAGE  "},
  { "     ", "iGNORE"},
  { "reap ", "CHAOS "},
  { "trace", "path  "},
  { "cut  ", "ties  "},
  { "FLip ", "tabLe "},
  { "Lift ", "spirIt"},
  { "bend ", "spoon "},
  { "ride ", "tide  "},
  { "raise", "roof  "},
  { "Cast ", "net   "},
  { "   de", "sCend "},
  { "you  ", "RULE  "},
  { "don't", "Change"},
  { "bEat ", "buSh  "},
  { "spice", "Up    "},
  { "DiP A", "tOE in"},
  { "play ", "Card  "},
  { "turn ", "tabLes"},
  { "hit  ", "naiL  "},
  { "2nd  ", "GUESS "},
  { "OPt  ", "OUt   "}
};
